---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  path: ./flux/staging
  prune: false
  serviceAccountName: instavote
  targetNamespace: instavote
  sourceRef:
    kind: GitRepository
    name: instavote-deploy  

